select * from customer limit 20


--1. what is the total revenue generated by the male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

--2. which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes'
and purchase_amount >= (select AVG(purchase_amount) from customer)
   

--3. which are the top 5  products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--4. compare the average purchase amounts between standard and express shipping?
select shipping_type,
ROUND(AVG(purchase_amount),2) 
from customer
where shipping_type IN ('Standard','Express')
group by shipping_type;

--5. do subcribed customers  spend more? compare average spend and total revenue between subcribers and non-subscribers?
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;


--6. which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate DESC
limit 5;

--7. segment customers into new, returning, and loyal based on their total number of previous purchases, and show the count of each segment?
with customer_type as (
select customer_id, previous_purchases,
case
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)

select customer_segment, COUNT(*) as "Number of Customers"
from customer_type
group by customer_segment;


--8. what are the top 3 most puchased products within tyhe each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

--9. are the customers who are repeat buyers (more than 5 previous purchases) alsolikely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--10. what ois the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;